-- Insert 50 Bot Profiles into the 'profiles' table
-- Run this script in the Supabase SQL Editor
-- This version uses gen_random_uuid() to generate IDs.

INSERT INTO profiles (id, username, high_score)
VALUES
    (gen_random_uuid(), 'Ravi.M@gmail.com', 3850),
    (gen_random_uuid(), 'Anitha_S', 2900),
    (gen_random_uuid(), 'karthik_raja', 5600),
    (gen_random_uuid(), 'Lakshmi_Priya', 2450),
    (gen_random_uuid(), 'arun.vijay@gmail.com', 4100),
    (gen_random_uuid(), 'Suresh_Babu', 3300),
    (gen_random_uuid(), 'Gowri_Shankar', 5100),
    (gen_random_uuid(), 'Divya.N@gmail.com', 1950),
    (gen_random_uuid(), 'Rajesh_Kannan', 4750),
    (gen_random_uuid(), 'Priya_Darshini', 1100),
    (gen_random_uuid(), 'geetha.r@gmail.com', 3150),
    (gen_random_uuid(), 'Venkatesh_Prabhu', 5050),
    (gen_random_uuid(), 'Revathi_S', 1750),
    (gen_random_uuid(), 'Saravanan_M', 6300),
    (gen_random_uuid(), 'preethi.k@gmail.com', 2700),
    (gen_random_uuid(), 'Dinesh_Kumar', 4000),
    (gen_random_uuid(), 'Kavitha_R', 1550),
    (gen_random_uuid(), 'Manikandan_S', 5700),
    (gen_random_uuid(), 'Sandhya.P@gmail.com', 2150),
    (gen_random_uuid(), 'Vijay_Sethupathi_Fan', 7800),
    (gen_random_uuid(), 'Trisha_Lover', 3700),
    (gen_random_uuid(), 'Ajith_Kumar_Fan', 7400),
    (gen_random_uuid(), 'subha.m@gmail.com', 2550),
    (gen_random_uuid(), 'Ganesh_Ram', 4500),
    (gen_random_uuid(), 'Malathi_K', 1350),
    (gen_random_uuid(), 'Balamurugan', 6000),
    (gen_random_uuid(), 'nithya.s@gmail.com', 3350),
    (gen_random_uuid(), 'Hari_Haran', 5300),
    (gen_random_uuid(), 'Lavanya_M', 1850),
    (gen_random_uuid(), 'Sathish_Kumar', 4850),
    (gen_random_uuid(), 'pooja.r@gmail.com', 2350),
    (gen_random_uuid(), 'Yuvan_Shankar', 6600),
    (gen_random_uuid(), 'Keerthi_Suresh', 3500),
    (gen_random_uuid(), 'Kamal_Hassan_Fan', 7100),
    (gen_random_uuid(), 'deepa.k@gmail.com', 2050),
    (gen_random_uuid(), 'Praveen_Kumar', 5000),
    (gen_random_uuid(), 'Swetha_R', 1650),
    (gen_random_uuid(), 'Ramesh_Babu', 6200),
    (gen_random_uuid(), 'vidya.m@gmail.com', 2850),
    (gen_random_uuid(), 'Ashok_Selvan', 4250),
    (gen_random_uuid(), 'Bhuvaneswari', 1250),
    (gen_random_uuid(), 'Chandru_M', 5800),
    (gen_random_uuid(), 'uma.devi@gmail.com', 2250),
    (gen_random_uuid(), 'Eswar_Moorthy', 4600),
    (gen_random_uuid(), 'Jaya_Shree', 1050),
    (gen_random_uuid(), 'Murugan_K', 5900),
    (gen_random_uuid(), 'chitra.s@gmail.com', 3050);
